### PR TITLE
A shy implementation with HTTPS/SSH support (connect)

### PR DESCRIPTION
**Pull request by ignacionr**
Hey, I'm a big fan of your work! Neat! I know that my style does not quite square but it's still only a few lines of code (other than the .NET 4.5 migration).
Tunneling is not re-implemented, just used from HttpSocket. Hope you like it, I think even as a shy and initial implementation, it'll push the project a lot further (since it'll be usable for tunneling).

### CODE REVIEW

**Comment by chendurkumar** [comment]
Hello Ignacio,
Thanks for your implementation ! 
I am interested to proceed further which includes decrypting the https Request and Response using self signed certificate. So can you help me how to start on this ? 

Thanks 
Kumar

**Comment by ignacionr** [comment]
That is a great idea! I also think that the folks that use this at Agoda will be interested too.
Can I come back to you in a few days?

-----Original Message-----

**Comment by krys-g** [comment]
Hi Kumar and Ignacio,

Kumar: Note that I no longer have time to work on Trotinet. But if Ignacio has a clean patch, I would be happy to merge it.

Regards,
krys

**Comment by ignacionr** [comment]
Kumar,

I went ahead and created a branch on my fork, added you to the repo. Please check out https://github.com/ignacionr/TrotiNet/tree/re-hashing-https ; we need to discuss how we want this to work (through "connect" I'm guessing?). Please check out any of my commits and see my email address there. Thank you!

Also thank you Krys! Ignacio.--

**Comment by chendurkumar** [comment]
Hi Ignacio,

Sorry for the delayed mail ! I was on vacation !

Thanks for coming back. As you have mentioned, you can come back to this
topic in few days, when your  time permits please write me about the
instruction to proceed.
Currently I looking into Fiddler project using Reflector. Seems they have
done much more stuff inside their project.

Also, If I am write I have start from the HandleConnect() // your shy
implementation

Currently i am also reading more about how https works :)

Waiting for your reply !

Cheers,
Kumar

**Comment by chendurkumar** [comment]
Hi Ignacio,

I couldn't get your email address from the commits. Could you pleas send me
an email so that we could start a discussion on this topic.

Also could you please help me how to proceed. I believe I could start from
the HandleConnect().

Waiting for you reply.

Thanks & Regards,
Kumar

**Pull request merged**
